#ifndef NearStatus_H_INCLUDED
#define NearStatus_H_INCLUDED





typedef enum _NearStatus {
    STATUS_SUCCESS, STATUS_UNKNOWN, STATUS_OUT_OF_MEMORY,
    STATUS_INIT_FAIL, STATUS_CANT_CREATE_ECS_COMP,
    STATUS_CANT_CREATE_ENTITY, STATUS_NOT_ENOUGH_MEMORY,
    STATUS_NO_VALID_MEMORY, STATUS_NOT_FOUND, STATUS_INVALID_PML_ENTRY,
    STATUS_NOT_MAPPED, STATUS_UACPI_INIT_FAIL, STATUS_ACPI_NAMESPACE_FAIL,
    STATUS_ACPI_GPE_FAIL, STATUS_REBOOT_FAILED, STATUS_SHUTDOWN_FAILED,
    STATUS_INVALID_ADDRESS, STATUS_ACCESS_DENIED, STATUS_CANT_FIND_HEADER,
    STATUS_PMM_FAIL, STATUS_VMM_FAIL, STATUS_GALLOC_FAIL, STATUS_TOO_LARGE,
    STATUS_INVALID_HANDLE, STATUS_INVALID_ENTITY, STATUS_NOT_IMPLEMENTED
} NearStatus;


#define NR_SUCCESS(x) (x == STATUS_SUCCESS)















#endif