target("nearldr-amd64")
    set_toolchains("clangpeamd64")
    set_filename("BOOTX64.efi")
    set_targetdir("../binaries/BOOT/")
    add_files("src/*.c", "src/externheaders/**/*.c", "src/arch/amd64/*.c", "src/arch/amd64/*.asm")
    add_cflags("-target x86_64-pc-win32-coff", "-fshort-wchar", "-ffreestanding", "-fno-stack-protector", "-fno-stack-check", "-fno-strict-aliasing", "-mno-red-zone", {force = true})
    add_asflags("-f win64", {force = true})
    add_ldflags("/machine:amd64 /subsystem:efi_application /entry:ldr_entry /dll /nodefaultlib", {force = true})

target("nearldr-aarch64")
    set_toolchains("clangpeaarch64")
    set_filename("BOOTAA64.efi")
    set_targetdir("../binaries/BOOT/")
    add_files("src/*.c", "src/externheaders/**/*.c", "src/arch/aarch64/*.c", "src/arch/aarch64/*.S")
    add_cflags("-target aarch64-pc-win32-coff", "-fshort-wchar", "-ffreestanding", "-fno-stack-protector", "-fno-stack-check", "-fno-strict-aliasing", {force = true})
    add_asflags("-target aarch64-pc-win32-coff", {force = true})
    add_ldflags("/machine:arm64 /subsystem:efi_application /entry:ldr_entry /dll /nodefaultlib", {force = true})
    
toolchain("clangpeamd64")
    set_kind("standalone")
    set_toolset("cc", "clang")
    set_toolset("as", "nasm", {force = true})
    add_asflags("-f win64", {force = true})
    set_toolset("ld", "lld-link")
toolchain_end()

toolchain("clangpeaarch64")
    set_kind("standalone")
    set_toolset("cc", "clang")
    set_toolset("as", "clang")
    set_toolset("ld", "lld-link")
toolchain_end()
