[target.x86_64-unknown-none]
linker = "ld"
rustflags = ["-C", "link-arg=-nostdlib", "-C", "link-arg=-Tlinkers/link-amd64.ld"]

[target.aarch64-unknown-none]
linker = "ld.lld"
rustflags = ["-C", "link-arg=-nostdlib", "-C", "link-arg=-Tlinkers/link-aarch64.ld"]
